const mongoose = require('mongoose');
const userdataSchema = new mongoose.Schema({
    _id:{
        type:String,
        required:true,
    },
    StudentName:{
        type:String,
        required:true,
    },
    Age:{
        type:Number,
        required:true,
    },
    School:{
        type:String,
        required:true,
    },
    Class:{
        type:Number,
        required:true,
    },
    MotherName:{
        type:String,
        required:true,
    },
    FatherName:{
        type:String,
        required:true,
    },
    MobileNumber:{
        type:String,
        required:true,
    },
    EmailId:{
        type:String,
        required:true,
    },
    HomeAddress:{
        type:String,
        required:true,
    },
    State:{
        type:String,
        required:true,
    },
    City:{
        type:String,
        required:true,
    },
    Pincode:{
        type:String,
        required:true,
    },
    PoliceStation:{
        type:String,
        required:true,
    },
    Country:{
        type:String,
        required:true,
    },
    ParentNumber:{
        type:String,
        required:true,
    },
    SchoolContact:{
        type:String,
        required:true,
    },
    BloodGroup:{
        type:String,
        required:true
    }

})
module.exports = mongoose.model('UserData', userdataSchema)